name: jest-tests

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        uses: willcaul/jest-github-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
